{% set version = "1.1.0rc10" %}
{% set sha256 = "19a4dfa8ad1a587ce304a79dc2f93e27edbfdd0d03cc2f07359282f77e9901da" %}

package:
  name: obspy
  version: {{ version }}

source:
  fn: obspy-{{ version }}.zip
  # url: https://pypi.io/packages/source/o/obspy/obspy-{{ version }}.zip
  url: https://www.dropbox.com/s/d92npjvy17yklma/obspy-1.1.0rc10.zip?dl=1
  sha256: {{ sha256 }}


build:
  number: 1
  preserve_egg_dir: yes
  detect_binary_files_with_prefix: true
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - future
    - numpy
    - scipy
    - matplotlib
    - lxml
    - sqlalchemy
    - requests
    - decorator
  run:
    - python
    - setuptools
    - future
    - numpy
    - scipy
    - matplotlib
    - lxml
    - sqlalchemy
    - requests
    - decorator
    - mock  # [py2k]

test:
  requires:
    - flake8
    - matplotlib
    - pyshp
  imports:
    - obspy
    - obspy.io.mseed
  commands:
    - python -c "from obspy import read;"
    # test at least a few executables that should've bben installed
    - obspy-print -h
    - obspy-plot -h
    - obspy-runtests -h
    - obspy-scan -h

about:
  home: https://obspy.org
  license: LGPLv3
  license_file: LICENSE.txt
  summary: "ObsPy: A Python Toolbox for seismology/seismological observatories."

extra:
  recipe-maintainers:
    - megies
    - krischer
    - barsch
    - QuLogic
    - ThomasLecocq
