{% set version = "1.2.0" %}
{% set sha256 = "b5956d21ecaffd954cbdff93129b8f571361b0f326203b99c5b57e0cd82b7f86" %}

package:
  name: obspy
  version: {{ version }}

source:
  fn: obspy-{{ version }}.zip
  url: https://pypi.io/packages/source/o/obspy/obspy-{{ version }}.zip
  # url: https://github.com/obspy/obspy/files/4297596/obspy-1.2.0rc9.zip
  sha256: {{ sha256 }}

build:
  number: 0
  preserve_egg_dir: yes
  detect_binary_files_with_prefix: true
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - future
    - numpy
    - scipy
    - matplotlib-base
    - lxml
    - sqlalchemy
    - requests
    - decorator
  run:
    - python
    - setuptools
    - future
    - numpy <1.16
    - scipy
    - matplotlib-base
    - lxml
    - sqlalchemy
    - requests
    - decorator
    - mock  # [py2k]
    - basemap
    # pyproj is a dep of basemap so it does not hurt to include it as dep right
    # now
    # dodge proj4 v5 for now, see obspy/obspy#2283
    - pyproj
    - proj4 !=5

test:
  requires:
    - flake8
    - matplotlib-base
    - pyshp
    - basemap
  imports:
    - obspy
    - obspy.io.mseed
  commands:
    - python -c "from obspy import read;"
    # test at least a few executables that should've bben installed
    - obspy-print -h  # [not win]
    - obspy-plot -h  # [not win]
    - obspy-runtests -h  # [not win]
    - obspy-scan -h  # [not win]

about:
  home: https://obspy.org
  license: LGPLv3
  license_file: LICENSE.txt
  summary: "ObsPy: A Python Toolbox for seismology/seismological observatories."
  description: |
    ObsPy is an open-source project dedicated to provide a Python framework for
    processing seismological data. It provides parsers for common file formats,
    clients to access data centers and seismological signal processing routines
    which allow the manipulation of seismological time series (see Beyreuther
    et al. 2010, Megies et al. 2011, Krischer et al. 2015).
  doc_url: http://docs.obspy.org/
  dev_url: https://github.com/obspy/obspy

extra:
  recipe-maintainers:
    - megies
    - krischer
    - barsch
    - QuLogic
    - ThomasLecocq
