travis:
  secure:
    BINSTAR_TOKEN: of7GCFqHLK4iJtuZGC4qFOzEfWmVqdnFsJdYtQsS3ADXyOcF3RRc0AJ75oCvHy92aWte+U0u6dVvIwESqWdxCPIvHE45NEJ+mezL/H+uap+Ad6JCMxTQpUK3TUVx/XBSy7rV6zsLLm8byMthPCf/mU4NiLZK9qzVUUyN+0FOvyFYrttBzlkplPQ2p8qF5g7vbu8VLOIzp6cN3NleSaFtdNx6G2HbzEyBENhxX6ZYcEsS/LtongT7PrWgobdT+Oxmy6Ut9V7nXrIkO+Q+AWh/K3nTPY1qLmLQ708VNiKT8Tuum9Id3xBJbbdOfZdceLO4QpLKqAcdB6LGFJqErwyvvKHt6BzJ7jcQLjkgYs1I3qqbGUdZ94jzV4h2JrfGX7UbrxyPDlEDXvrBfCJ+9LBeTd5cAredlVKMfL4qSrreo1yQ9H5/FEubF18FhktXRpoFQQhINigB40wuHG+6gctytD6yopaqtRbSoCuCrvgFgi69A6DSt0Wnf48wnk26e34oHn06qQYV4qmj4G2Ec6uvjeDv2uwananda6ZVUNuL4xEJuc0CSCszr77+dZ6u0a5TITQKlx+JGuncqO3I0KShL4qDepbFhUAdGu6Z4v/yQYL48QwA4q7GhJLS0hBTecU1CMf1ellbvW90eu+ffB8xCuEeAfkMo211G3vVvBVED4E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
max_py_ver: '37'
