travis:
  secure:
    BINSTAR_TOKEN: OOSuFnEIzpApxnGlTTV4WjKbMN43Ku7KbUuv4nXcn6Uu+HG0ZKIVHPqIkFq7Nkbv3Ang+jVZJk07mxYNxcUhcU3778tyC8BiAxq4WtRigeqNAPPvp7jNCPt2KDCF2o0eZB2Pgh6Q0E+DxywgAD4wMhwcXXeUZkQWeQI+AZP9ZZ+FGK2U+B4kNPMsh+o9P3VTXqZCAT9EwyWJPDUSyKySHLXaHvw5bZD0f/McJ1MQz2JvFX67AWD9HRrdkvX06QUfiBmIyZRguG4mrT5KRDW6j+pVQSF4Z92PYktnfKX5soQlqBgEP/k/h6jyjLKzVQGYL5j+FneKONJqdgnYk4UkAvmQ4V4KjNiUGOmkGJKW6UEqeFL4F2KD/HOV4rIh8TaGKdtVRuTm4hLtQSMfQXA1v1yy3LuB9RDSffPF4rvsWo4spEigznaFz642TOQecK3ouZlrCUhaBJQm8S2HrMocdrwffW3z6y/a5Gc+Oi3ehDRvac/qSefeO7m3XwLXS3nRUC50NmLntfSO0+ncxQmLAxPh31tEfVMwZkdeoyTfvsTlgmYG2vz8lbrdrRM8nfvYNM3UJR9Te34njRzHBgHqJB0vduIih3JTUt8IWsmWQOsPqn1nilQdKeFiIU0RW8VrR+/4M9QsB7SudKm0uFhXUrRFHizMJQ1pyeOOmQknyOU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
